require 'helper'

describe AllPlayers::Client do
  describe "Event" do
    before :all do
      # Create Group.
      $group_title = (0...8).map{65.+(rand(25)).chr}.join
      more_params = {}
      $location = {
        :street => '122 Main ',
        :additional => 'Suite 303',
        :city => 'Lewisville',
        :province => 'TX',  # <-- Test Breaker!
        :postal_code => '75067',
        :country => 'us',
      }
      begin
        $group = $apci_session.group_create(
          $group_title,
          'This is a test group generated by event_spec.rb',
          $location,
          ['Sports', 'Baseball'],
          'Other',
          more_params
        )
      rescue
        pending "until we allow group creation with our API."
      end

      # Create Event.
      $event_title = (0...8).map{65.+(rand(25)).chr}.join
      more_params = {}
      begin
        $event = $apci_session.event_create(
          $event_title,
          'This is a test event generated by event_spec.rb',
          $group['nid'],
          '2012-09-15T08:05:00', # Generic Date
          '2012-09-15T08:05:00',
          nil,
          more_params = {}
        )
      rescue
        pending "until we allow event creation with our API."
      end
    end

    it "should be created properly." do
      $event['nid'].should_not == nil
    end

    it "should be able to update", :testing do
      event = $apci_session.event_create(
        $event_title,
        'This is a test event updated by event_spec.rb',
        $group['nid'],
        '2012-09-15T08:05:00', # Generic Date
        '2012-09-15T08:05:00',
        $event['nid'],
        more_params = {}
      )
      event.should_not == nil
    end
  end
end