require 'helper'

describe AllPlayers::Client do
  describe "Event" do
    before :all do
      # Create Group.
      $group_title = (0...8).map{65.+(rand(25)).chr}.join
      more_params = {}
      $location = {
        :street => '122 Main ',
        :city => 'Lewisville',
        :state => 'TX',
        :zip => '75067',
      }
      $group = $apci_session.group_create_public(
        $group_title,
        'This is a test group generated by event_spec.rb',
        $location,
        ['Sports', 'Baseball'],
        more_params
      )
      
      # Create Event.
      $event_title = (0...8).map{65.+(rand(25)).chr}.join
      more_params = {}
      $event = $apci_session.event_create(
        $event_title,
        'This is a test event generated by event_spec.rb',
        $group['uuid'],
        '2012-09-15T08:05:00', # Generic Date
        '2012-09-15T09:05:00',
        more_params = {}
      )
    end

    it "should be created properly." do
      $event['title'].should == $event_title
      $event['groups']['item'].should include($group['uuid'])
    end

    it "should be able to update" do
      pending "until we fix error on event update."
      updated_description = 'This is a test event updated by event_spec.rb'
      update_params = {
        :description => updated_description
      }
      event = $apci_session.event_update(
        $event['uuid'],
        update_params
      )
      event['description'].should == updated_description
    end
  end
end