require 'helper'

describe AllPlayers::Client do
  describe "Node" do
    before :all do
      $title = (0...8).map{65.+(rand(25)).chr}.join
      $body = 'This is a test node generated by node_spec.rb'
      $node = $apci_session.node_create(
        $title,
        'book',
        $body
      )
    end

    it "should be created properly." do
      $node['nid'].should_not == nil
      node = $apci_session.node_get($node['nid'])
      node['title'].should == $title
      node['body'].should == $body
      node['type'].should == 'book'
    end

    it "should be retrievable. (get)" do
      node = $apci_session.node_get($node['nid'])
      node['nid'].should == $node['nid']
    end

    it "should be able to update." do
      node = $node

      body = $body + ' Testing update, blah, blah, blah.'
      more_params = { :body => body }
      update_response = $apci_session.node_update(node['nid'], more_params)
      update_response['nid'].should == node['nid']
      updated_node = $apci_session.node_get(node['nid'])
      updated_node['nid'].should == node['nid']
      updated_node['title'].should == $title
      updated_node['body'].should == body
      updated_node['type'].should == 'book'
    end

    it "should list nodes." do
      nid = $node['nid']
      nodes = $apci_session.node_list({:nid => nid.to_s})
      nodes['item'].first['nid'].should == nid.to_s
    end

    it "should be able to attach files." do
      remote_file = open('http://www.google.com/images/logos/ps_logo2.png') {|f| f.read }
      file_data = {:filename => 'ps_logo.png', :file => remote_file}
      response = $apci_session.file_create(file_data)
      response['fid'].should_not == nil

      file = $apci_session.file_get(response['fid'], true)
      file['fid'].should == response['fid']
      file['contents'].should_not == nil
      remote_file.should == file['contents']

      random_title = (0...8).map{65.+(rand(25)).chr}.join
      more_params = {
        :field_logo => {0 => {'fid' => response['fid']}}
      }
      location = {
        :street => '122 Main ',
        :additional => 'Suite 303',
        :city => 'Lewisville',
        :province => 'TX',
        :postal_code => '75067',
        :country => 'us',
      }

      group_response = $apci_session.group_create(
       random_title,
       'This is a test group generated by test_apci_rest.rb',
       location,
       ['Sports', 'Baseball'],
       'Other',
       more_params
      )

      group_response['nid'].should_not == nil
      group = $apci_session.node_get(group_response['nid'])
      group['field_logo']['item'].first['fid'].should == response['fid']
    end
  end
end
