require 'helper'

describe AllPlayers::Client do
  describe "Node Create" do
    before :all do
      $title = (0...8).map{65.+(rand(25)).chr}.join
      $body = 'This is a test node generated by test_apci_rest.rb'
      $node = $apci_session.node_create(
        $title,
        'book',
        $body
      )
    end

    it "should be created properly." do
      $node['nid'].should_not == nil
      node = $apci_session.node_get($node['nid'])
      node['title'].should == $title
      node['body'].should == $body
      node['type'].should == 'book'
    end
  end
end